"""
Equalizer APO Bridge:
Generates Equalizer APO configuration syntax and safely writes updates
directly to the active Equalizer APO config pipeline with atomic file writes.
"""

from pathlib import Path
from typing import Tuple
from .config import SettingsManager


class ApoBridge:
    def __init__(self, settings: SettingsManager):
        self.settings = settings

    def generate_apo_config_content(self) -> str:
        """
        Builds the Equalizer APO configuration text.
        If bypass is ON, filters are omitted and preamp is 0 dB.
        Otherwise, outputs Preamp and Peaking (PK) biquad filters for each band.
        """
        lines = [
            "# ========================================================",
            "# Equalizer APO configuration generated by PulseEQ",
            "# Live-synchronized in real time (Zero latency audio DSP)",
            "# ========================================================",
            ""
        ]

        if self.settings.bypass:
            lines.append("# Master Equalizer Bypass is ACTIVE")
            lines.append("Preamp: 0.0 dB")
            for i, freq in enumerate(self.settings.frequencies):
                lines.append(f"Filter {i + 1}: OFF PK Fc {freq:.0f} Hz Gain 0.0 dB Q 1.41")
            return "\n".join(lines) + "\n"

        # Apply preamp gain
        lines.append(f"Preamp: {self.settings.preamp:.1f} dB")
        lines.append("")

        # Apply each band filter
        for i, (freq, gain, q) in enumerate(
            zip(self.settings.frequencies, self.settings.gains, self.settings.q_factors)
        ):
            status = "ON" if abs(gain) >= 0.05 else "OFF"
            lines.append(f"Filter {i + 1}: {status} PK Fc {freq:.0f} Hz Gain {gain:.1f} dB Q {q:.2f}")

        return "\n".join(lines) + "\n"

    def apply_config(self) -> Tuple[bool, str]:
        """
        Writes the generated configuration to py_equalizer.txt atomically.
        Ensures Equalizer APO's main config.txt includes py_equalizer.txt.
        """
        target_file = self.settings.get_output_config_path()
        content = self.generate_apo_config_content()

        try:
            target_file.parent.mkdir(parents=True, exist_ok=True)

            # Atomic write via temporary file
            temp_file = target_file.with_suffix(".tmp")
            with open(temp_file, "w", encoding="utf-8") as f:
                f.write(content)
            temp_file.replace(target_file)

            # Ensure main config.txt includes our file
            self._ensure_included_in_main_config()

            return True, f"Config successfully synced to {target_file}"
        except PermissionError:
            msg = (
                f"Permission denied writing to '{target_file}'. "
                "Run as Administrator or configure folder write permissions for Equalizer APO config."
            )
            print(f"[APO Bridge] {msg}")
            return False, msg
        except Exception as e:
            msg = f"Failed to sync config: {e}"
            print(f"[APO Bridge] {msg}")
            return False, msg

    def _ensure_included_in_main_config(self):
        """
        If main config.txt exists, verify that 'Include: py_equalizer.txt' is in it.
        If not, append it without overwriting existing filters or device tags.
        """
        main_cfg = self.settings.get_main_apo_config_path()
        if not main_cfg.exists():
            return

        try:
            with open(main_cfg, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()

            include_directive = "Include: py_equalizer.txt"
            if include_directive not in content:
                with open(main_cfg, "a", encoding="utf-8") as f:
                    f.write(f"\n# Include Python Web Equalizer config\n{include_directive}\n")
                print(f"[APO Bridge] Added '{include_directive}' to {main_cfg}")
        except Exception as e:
            print(f"[APO Bridge] Note: Could not update main config.txt: {e}")
